name: Deploy Spring boot to Amazon EC2

env:
  APPLICATION_NAME: issue-tracker-code-deploy
  S3_BUCKET_NAME: lambda-deploy-test-joaquin
  PROJECT_NAME: issue-tracker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        working-directory: ./BE/issue_tracker/
      
      - name: Build with Gradle
        run: ./gradlew bootjar -x test
        shell: bash
        working-directory: ./BE/issue_tracker/
        
      - name: Make zip file
        run: zip -qq -r ./issue-tracker.zip .
        shell: bash   
        working-directory: ./BE/issue_tracker
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}} 
          aws-region: us-east-2

      - name: Upload to S3
        run: aws s3 cp --region us-east-2 ./BE/issue_tracker/issue-tracker.zip s3://lambda-deploy-test-joaquin/$PROJECT_NAME/issue-tracker.zip
        
      - name: Code Deploy
        run: aws deploy create-deployment --application-name $APPLICATION_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/issue-tracker.zip
